### ISSUE TITLE
NullPointerException when trying to get completions

### ISSUE THREAD

**Issue by PranavPurwar** [tyron12233/JavaCompletions#2]
I'm unable to use this library in my project.

Whenever I try to run the sample project, it just throws an NPE saying treePath is null, I tried searching for the cause of this issue but it refers to AutoValue_PositionContext.java which is auto-generated by the AutoValue annotations library.
Here's the code I'm currently using
```java
JavaCompletions completions = new JavaCompletions();
completions.initialize(new File(/* Path to the directory containing the sample java files */).toURI(), new JavaCompletionOptionsImpl(getBinDir() + "log.txt", Level.ALL, null, null));
// As a sample test
CompletionResult result = completions.getProject()
                .getCompletionResult(new File(currentPathOfFile).toPath(), 8 /** line **/, 13 /** column **/);
 
String s = "";

for(CompletionCandidate candidate : result.getCompletionCandidates()) {
    s += candidate.getName();
    s += "\n";
}
/* Do something with the completion list later on */
```

Note: I modified the library to use com.sun.* and javax.tools.* packages instead of org.openjdk.* and org.openjdk.javax.* packages by mass search and replace
![Screenshot_2022-05-06-18-06-53-437_com pranav java ide](https://user-images.githubusercontent.com/75154889/167132943-0dcca2d4-ced5-4b20-b8c5-e8de6b905caa.jpg)
![Screenshot_2022-05-06-18-07-18-709_com pranav java ide](https://user-images.githubusercontent.com/75154889/167132958-6baad321-f2bf-4f1d-b1cf-c35c95267869.jpg)

**Comment by tyron12233** [comment]
the NPE was caused my the modification of the packages, please try using the ones that is packaged in the library because thats the one that is tested.
